import './globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'AutoVulcano',
  description: 'Generated by Vinicius Rodrigues and William Vulcano',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster position='top-center'/>
      </body>
    </html>
  )
}
